title: scottstaniewicz.com
logo: site-logo.png
search: true
url: https://scottstaniewicz.com

# Jekyll configuration
permalink:   /:title/

plugins:
  - jekyll-sitemap

# Make the default layout the "default"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "sidebar"
  - scope:
      path: "_posts"
    values:
      layout: "sidebar"

include: [".htaccess"]
exclude: [ "Gemfile", "Gemfile.lock", "README.md"]

# Site owner
owner:
  name: Scott Staniewicz
  email: scott.stanie@gmail.com
  github: scottstanie
